version: "3.9"
services:
  producer:
    build: .
    container_name: producer
    volumes:
      - ./shared_volume:/app/shared_volume
    env_file: .env

  spark:
    image: bitnami/spark:latest
    container_name: spark
    volumes:
      - ./spark:/app/spark
      - ./shared_volume:/app/shared_volume
    working_dir: /app
    command: >
      bash -c "sleep 5 && /opt/bitnami/spark/bin/spark-submit /app/spark/spark_streamer.py"
    depends_on:
      - producer
  dash:
    build: .
    container_name: dash
    ports:
      - "8050:8050"
    volumes:
      - ./shared_volume:/app/shared_volume
    depends_on:
      - spark
    command: python dash/dashboard.py
